### PR TITLE
feat: updated to use React 18 streaming

### PR DESCRIPTION
**Pull request by jacob-ebey**

### CODE REVIEW

**Review by 3imed-jaberi — APPROVED** [review]
LGTM

**Review by ascorbic — APPROVED** [review]
Nice! LGTM

**Comment by CanRau** [comment]
as mentioned here https://github.com/remix-run/remix/issues/2570#issuecomment-1105840907 same now happens with the https://remix-edge-on.netlify.app/ example, content flickers shortly before vanishing leaving me with

```
Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```
which translates to 
```
The full text of the error you just encountered is:
Hydration failed because the initial UI does not match what was rendered on the server.
```

**Comment by nickytonline** [comment]
@CanRau, just going to wait on this to see what they come up with in https://github.com/remix-run/remix/issues/2570.

**Comment by CanRau** [comment]
Yea sounds good 👌

**Pull request merged**
